# Generated by Django 2.1.3 on 2018-11-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('person', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('MV', 'Movie'), ('BK', 'Book'), ('TV', 'TV Series'), ('RL', 'Real Life'), ('OT', 'Other')], max_length=20)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('fk_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_users.User')),
            ],
        ),
    ]
